name: relfree-test
on:
  workflow_dispatch:
jobs:
  t:
    uses: wppoland/workflows/.github/workflows/_min.yml@main
    with:
      slug: restock
      dry-run: true
    secrets:
      WPORG_SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
